# -*- coding: utf-8 -*-
"""gated_newton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bw-VRZgeQXCMlZtYMD2kXZFb-BKfyuHi

# Using our rule as an optimizer

I guess this is more of a cautionary tale... (the RSAs are the same to error :()

This notebook implements the **optimiser-side** comparison discussed in the TeX, using the same model families across tasks:

1. SGD  
2. SGD with momentum  
3. Damped Newton-CG  
4. Gated damped Newton-CG  

(The reason we use CG, per the feedback, is that the Hessian on using Newton Raphson fully is pretty disgusting and I couldn't get stable or nice compute with it. Also, I wanted to pick some conventional descent methods, especially since I'm learning about them in another class, and CG and SGD are that.)

The idea here is that all methods minimise the same supervised objective. The proposed third factor is **not** treated as a standalone local objective here. Instead, it is used only in the **gated Newton-CG** condition to modulate the **unitwise damping** inside a damped Newton step.

The default tasks are:
- **CIFAR-100** for harder object classification
- **Haxby** for the fMRI decoding analysis

To keep the second-order methods tractable, the common model family is a **small one-hidden-layer MLP** with ReLU. This was meant to be a toy that can still approach the tasks from Lv, and it does end up doing this.

This cell installs Nilearn for Haxby, then imports the PyTorch, plotting, and sklearn tools used throughout the notebook.
"""

#!pip -q install nilearn nibabel scikit-learn

import math
import random
import time
from dataclasses import dataclass, asdict
from collections import defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils import parameters_to_vector
from torch.utils.data import DataLoader, Subset, TensorDataset
from torchvision import datasets, transforms

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import GroupKFold
from sklearn.decomposition import PCA

from nilearn import datasets as nilearn_datasets
from nilearn.maskers import NiftiMasker

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

"""
This cell defines seed control, a small shared MLP, and a few small helper dataclasses used to store diagnostics."""

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


class SmallMLP(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, output_dim: int):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim, bias=True)
        self.fc2 = nn.Linear(hidden_dim, output_dim, bias=True)

        nn.init.normal_(self.fc1.weight, mean=0.0, std=0.02)
        nn.init.zeros_(self.fc1.bias)
        nn.init.normal_(self.fc2.weight, mean=0.0, std=0.02)
        nn.init.zeros_(self.fc2.bias)

    def hidden(self, x: torch.Tensor) -> torch.Tensor:
        return F.relu(self.fc1(x))

    def forward(self, x: torch.Tensor):
        h = self.hidden(x)
        logits = self.fc2(h)
        return logits, h


@dataclass
class GateState:
    prev_mean: torch.Tensor
    trace: torch.Tensor


@dataclass
class StepRecord:
    epoch: int
    step: int
    wall_time: float
    train_loss: float
    train_acc: float
    grad_norm: float
    update_norm: float
    param_norm: float
    gate_mean: float | None
    gate_sat: float | None
    damping_mean: float | None
    damping_min: float | None
    damping_max: float | None


@dataclass
class RunSummary:
    task: str
    method: str
    seed: int
    final_test_loss: float
    final_test_acc: float
    best_test_acc: float
    total_wall_time: float
    unstable: bool
    hidden_weight_norm: float
    output_weight_norm: float

"""
This cell provides:
- standardised CIFAR-100 loading
- Haxby loading with some preprocessing described in Lv
- group-aware train/test splits for Haxby"""

def make_cifar100_loaders(
    batch_size: int = 256,
    train_subset: int | None = None,
    test_subset: int | None = None,
    root: str = "./data",
):
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.5071, 0.4867, 0.4408),
            std=(0.2675, 0.2565, 0.2761),
        ),
    ])

    train_ds = datasets.CIFAR100(root=root, train=True, download=True, transform=transform)
    test_ds = datasets.CIFAR100(root=root, train=False, download=True, transform=transform)

    if train_subset is not None:
        train_ds = Subset(train_ds, list(range(min(train_subset, len(train_ds)))))
    if test_subset is not None:
        test_ds = Subset(test_ds, list(range(min(test_subset, len(test_ds)))))

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

    input_dim = 32 * 32 * 3
    num_classes = 100
    return train_loader, test_loader, input_dim, num_classes


def load_haxby_arrays(
    subject_id: int = 2,
    use_vt_mask: bool = True,
    keep_scrambledpix: bool = False,
    pca_components: int | None = 128,
):
    haxby = nilearn_datasets.fetch_haxby(subjects=[subject_id])
    session_df = pd.read_csv(haxby.session_target[0], sep=r"\s+")

    label_col = "labels" if "labels" in session_df.columns else "condition"
    group_col = "chunks" if "chunks" in session_df.columns else "chunk"

    if use_vt_mask and hasattr(haxby, "mask_vt"):
        mask_img = haxby.mask_vt[0] if isinstance(haxby.mask_vt, (list, tuple)) else haxby.mask_vt
    else:
        mask_img = haxby.mask[0] if isinstance(haxby.mask, (list, tuple)) else haxby.mask

    masker = NiftiMasker(mask_img=mask_img, standardize=True, detrend=False)
    X_full = masker.fit_transform(haxby.func[0])

    keep = session_df[label_col].astype(str) != "rest"
    if not keep_scrambledpix:
        keep = keep & (session_df[label_col].astype(str) != "scrambledpix")

    X = X_full[keep.values]
    y_text = session_df.loc[keep, label_col].astype(str).to_numpy()
    groups = session_df.loc[keep, group_col].to_numpy()

    encoder = LabelEncoder()
    y = encoder.fit_transform(y_text)

    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    if pca_components is not None:
        n_comp = min(pca_components, X.shape[0] - 1, X.shape[1])
        if n_comp >= 2:
            pca = PCA(n_components=n_comp, random_state=0)
            X = pca.fit_transform(X)

    return X.astype(np.float32), y.astype(np.int64), groups, encoder


def make_array_loaders(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    batch_size: int = 128,
):
    train_ds = TensorDataset(
        torch.tensor(X_train, dtype=torch.float32),
        torch.tensor(y_train, dtype=torch.long),
    )
    test_ds = TensorDataset(
        torch.tensor(X_test, dtype=torch.float32),
        torch.tensor(y_test, dtype=torch.long),
    )
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)
    return train_loader, test_loader

"""
This cell defines the proposed accelerometer gate and turns it into a **unitwise damping vector** for the gated Newton-CG method."""

@torch.no_grad()
def update_gate_from_hidden(
    hidden: torch.Tensor,
    state: GateState,
    alpha: float,
    g_max: float,
):
    current_mean = hidden.mean(dim=0)
    delta = current_mean - state.prev_mean
    rise = torch.relu(delta)
    state.trace = alpha * state.trace + (1.0 - alpha) * rise
    gate = torch.clamp(state.trace, 0.0, g_max)
    state.prev_mean = current_mean.detach()

    sat = float((gate >= g_max - 1e-8).float().mean().item())
    return gate.detach(), float(gate.mean().item()), sat


def make_hidden_gate_state(hidden_dim: int, device: torch.device):
    return GateState(
        prev_mean=torch.zeros(hidden_dim, device=device),
        trace=torch.zeros(hidden_dim, device=device),
    )


def make_damping_vector(
    model: SmallMLP,
    base_damping: float,
    hidden_gate: torch.Tensor | None = None,
    kappa: float = 1.0,
):
    # fc1.weight: [hidden_dim, input_dim]
    # fc1.bias:   [hidden_dim]
    # fc2.weight / fc2.bias: use base damping
    hidden_dim, input_dim = model.fc1.weight.shape

    if hidden_gate is None:
        hidden_lambdas = torch.full((hidden_dim,), base_damping, device=model.fc1.weight.device)
    else:
        hidden_lambdas = base_damping / (1.0 + kappa * hidden_gate)

    v1 = hidden_lambdas.repeat_interleave(input_dim)
    v2 = hidden_lambdas
    v3 = torch.full_like(model.fc2.weight.data.reshape(-1), base_damping)
    v4 = torch.full_like(model.fc2.bias.data.reshape(-1), base_damping)

    damping_vec = torch.cat([v1, v2, v3, v4], dim=0)
    stats = {
        "mean": float(damping_vec.mean().item()),
        "min": float(damping_vec.min().item()),
        "max": float(damping_vec.max().item()),
    }
    return damping_vec, stats

"""
This cell implements a truncated conjugate-gradient solve for the damped Newton system using Hessian-vector products from autograd. The Hessian is never formed explicitly."""

def _params(model):
    return [p for p in model.parameters() if p.requires_grad]


def _vectorize_params(params):
    return parameters_to_vector([p.detach().clone() for p in params])


def _assign_vector_to_params(vec, params):
    offset = 0
    for p in params:
        numel = p.numel()
        p.copy_(vec[offset:offset + numel].view_as(p))
        offset += numel


def conjugate_gradients_safe(Av, b, max_iter: int = 10, tol: float = 1e-4, eps: float = 1e-10):
    x = torch.zeros_like(b)
    r = b - Av(x)
    p = r.clone()
    rs_old = torch.dot(r, r)

    if not torch.isfinite(rs_old):
        return x, {"status": "nonfinite_init", "iters": 0}

    for k in range(max_iter):
        Ap = Av(p)

        if not torch.isfinite(Ap).all():
            return x, {"status": "nonfinite_Ap", "iters": k}

        denom = torch.dot(p, Ap)

        # CG needs positive curvature; bail out if curvature is bad or nearly singular
        if (not torch.isfinite(denom)) or (denom <= eps):
            return x, {"status": "bad_curvature", "iters": k}

        alpha = rs_old / denom

        if not torch.isfinite(alpha):
            return x, {"status": "nonfinite_alpha", "iters": k}

        x = x + alpha * p
        r = r - alpha * Ap
        rs_new = torch.dot(r, r)

        if not torch.isfinite(rs_new):
            return x, {"status": "nonfinite_residual", "iters": k + 1}

        if torch.sqrt(rs_new) < tol:
            return x, {"status": "converged", "iters": k + 1}

        beta = rs_new / rs_old.clamp_min(eps)

        if not torch.isfinite(beta):
            return x, {"status": "nonfinite_beta", "iters": k + 1}

        p = r + beta * p
        rs_old = rs_new

    return x, {"status": "max_iter", "iters": max_iter}


def hvp_from_loss(loss, params, vec):
    grads = torch.autograd.grad(loss, params, create_graph=True, retain_graph=True)
    gvec = parameters_to_vector([g.contiguous() for g in grads])
    dot = torch.dot(gvec, vec)
    hv_parts = torch.autograd.grad(dot, params, retain_graph=True)
    hv = parameters_to_vector([h.contiguous() for h in hv_parts])
    return gvec, hv


def newton_cg_step(
    model: SmallMLP,
    xb: torch.Tensor,
    yb: torch.Tensor,
    lr: float,
    base_damping: float,
    max_cg_iter: int,
    cg_tol: float,
    hidden_gate: torch.Tensor | None = None,
    kappa: float = 1.0,
):
    model.zero_grad(set_to_none=True)

    xb = prepare_mlp_input(xb)

    logits, hidden = model(xb)
    loss = F.cross_entropy(logits, yb)

    params = _params(model)

    damping_vec, damping_stats = make_damping_vector(
        model=model,
        base_damping=base_damping,
        hidden_gate=hidden_gate,
        kappa=kappa,
    )

    zero_vec = torch.zeros_like(_vectorize_params(params))
    gvec, _ = hvp_from_loss(loss, params, zero_vec)
    gvec = gvec.detach()

    if (not torch.isfinite(gvec).all()) or (not torch.isfinite(loss)):
        return {
            "loss": float("nan"),
            "acc": float("nan"),
            "grad_norm": float("nan"),
            "update_norm": float("nan"),
            "param_norm": float("nan"),
            "damping_mean": damping_stats["mean"],
            "damping_min": damping_stats["min"],
            "damping_max": damping_stats["max"],
            "hidden": hidden.detach(),
            "cg_status": "nonfinite_grad",
            "cg_iters": 0,
            "step_scale": 0.0,
        }

    grad_norm = float(gvec.norm().item())

    def Av(v):
        _, hv = hvp_from_loss(loss, params, v)
        out = hv.detach() + damping_vec.detach() * v
        if not torch.isfinite(out).all():
            raise RuntimeError("Nonfinite HVP in Av")
        return out

    try:
        p, cg_info = conjugate_gradients_safe(
            Av=Av,
            b=gvec,
            max_iter=max_cg_iter,
            tol=cg_tol,
        )
    except RuntimeError:
        p = gvec.clone()
        cg_info = {"status": "runtime_error_fallback_grad", "iters": 0}

    if (not torch.isfinite(p).all()) or cg_info["status"] not in {"converged", "max_iter"}:
        p = gvec.clone()
        cg_info["status"] = f"fallback_grad_{cg_info['status']}"

    theta0 = _vectorize_params(params)
    base_loss = float(loss.item())

    step_scale = lr
    accepted = False
    update = None

    with torch.no_grad():
        for _ in range(8):
            update = step_scale * p
            theta_trial = theta0 - update
            _assign_vector_to_params(theta_trial, params)

            logits_trial, _ = model(xb)
            loss_trial = F.cross_entropy(logits_trial, yb)

            if torch.isfinite(loss_trial) and float(loss_trial.item()) <= base_loss:
                accepted = True
                break

            step_scale *= 0.5

        if not accepted:
            _assign_vector_to_params(theta0, params)
            step_scale = min(1e-3, lr * 0.01)
            update = step_scale * gvec
            theta_trial = theta0 - update
            _assign_vector_to_params(theta_trial, params)
            cg_info["status"] = f"{cg_info['status']}_tiny_grad_fallback"

    with torch.no_grad():
        logits_after, _ = model(xb)
        batch_acc = float((logits_after.argmax(dim=1) == yb).float().mean().item())
        param_norm = float(_vectorize_params(params).norm().item())
        update_norm = float(update.norm().item()) if update is not None else 0.0

    return {
        "loss": float(loss.item()),
        "acc": batch_acc,
        "grad_norm": grad_norm,
        "update_norm": update_norm,
        "param_norm": param_norm,
        "damping_mean": damping_stats["mean"],
        "damping_min": damping_stats["min"],
        "damping_max": damping_stats["max"],
        "hidden": hidden.detach(),
        "cg_status": cg_info["status"],
        "cg_iters": cg_info["iters"],
        "step_scale": step_scale,
    }

"""
This cell defines the shared SGD / SGD-with-momentum step, so that all four methods can be run through a common training driver."""

def first_order_step(
    model: SmallMLP,
    xb: torch.Tensor,
    yb: torch.Tensor,
    optimizer: torch.optim.Optimizer,
):
    model.zero_grad(set_to_none=True)
    logits, hidden = model(xb)
    loss = F.cross_entropy(logits, yb)
    loss.backward()

    grad_vec = parameters_to_vector([p.grad.detach() for p in model.parameters() if p.grad is not None])
    grad_norm = float(grad_vec.norm().item())

    theta_before = parameters_to_vector([p.detach().clone() for p in model.parameters()])
    optimizer.step()
    theta_after = parameters_to_vector([p.detach() for p in model.parameters()])
    update_norm = float((theta_after - theta_before).norm().item())

    with torch.no_grad():
        logits_after, _ = model(xb)
        batch_acc = float((logits_after.argmax(dim=1) == yb).float().mean().item())

    return {
        "loss": float(loss.item()),
        "acc": batch_acc,
        "grad_norm": grad_norm,
        "update_norm": update_norm,
        "param_norm": float(theta_after.norm().item()),
        "damping_mean": None,
        "damping_min": None,
        "damping_max": None,
        "hidden": hidden.detach(),
    }

"""
This cell runs one full training experiment for any of the four methods and stores both stepwise diagnostics and a run summary."""

@torch.no_grad()
def evaluate_model(model: SmallMLP, loader: DataLoader, device: torch.device):
    model.eval()
    total = 0
    total_loss = 0.0
    correct = 0
    for xb, yb in loader:
        xb = xb.to(device)
        yb = yb.to(device)
        if xb.ndim > 2:
            xb = xb.view(xb.size(0), -1)
        logits, _ = model(xb)
        loss = F.cross_entropy(logits, yb, reduction="sum")
        total_loss += float(loss.item())
        correct += int((logits.argmax(dim=1) == yb).sum().item())
        total += yb.size(0)
    return total_loss / max(total, 1), correct / max(total, 1)


def train_one_run(
    task_name: str,
    method: str,
    train_loader: DataLoader,
    test_loader: DataLoader,
    input_dim: int,
    output_dim: int,
    seed: int = 0,
    hidden_dim: int = 256,
    epochs: int = 10,
    lr: float = 0.05,
    momentum: float = 0.9,
    base_damping: float = 1.0,
    alpha: float = 0.9,
    g_max: float = 1.0,
    kappa: float = 2.0,
    max_cg_iter: int = 10,
    cg_tol: float = 1e-4,
):
    set_seed(seed)
    model = SmallMLP(input_dim=input_dim, hidden_dim=hidden_dim, output_dim=output_dim).to(device)

    if method == "sgd":
        optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.0)
    elif method == "sgd_momentum":
        optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=momentum)
    else:
        optimizer = None

    gate_state = make_hidden_gate_state(hidden_dim=hidden_dim, device=device)
    step_records = []
    unstable = False
    t0 = time.time()
    global_step = 0
    best_test_acc = 0.0

    for epoch in range(1, epochs + 1):
        model.train()
        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            if xb.ndim > 2:
                xb = xb.view(xb.size(0), -1)

            global_step += 1
            gate_mean = None
            gate_sat = None

            try:
                if method in {"sgd", "sgd_momentum"}:
                    out = first_order_step(model, xb, yb, optimizer)
                elif method == "damped_newton_cg":
                    out = newton_cg_step(
                        model=model,
                        xb=xb,
                        yb=yb,
                        lr=lr,
                        base_damping=base_damping,
                        max_cg_iter=max_cg_iter,
                        cg_tol=cg_tol,
                        hidden_gate=None,
                        kappa=kappa,
                    )
                elif method == "gated_damped_newton_cg":
                    with torch.no_grad():
                        _, hidden_pre = model(xb)
                        hidden_gate, gate_mean, gate_sat = update_gate_from_hidden(
                            hidden=hidden_pre,
                            state=gate_state,
                            alpha=alpha,
                            g_max=g_max,
                        )

                    out = newton_cg_step(
                        model=model,
                        xb=xb,
                        yb=yb,
                        lr=lr,
                        base_damping=base_damping,
                        max_cg_iter=max_cg_iter,
                        cg_tol=cg_tol,
                        hidden_gate=hidden_gate,
                        kappa=kappa,
                    )
                else:
                    raise ValueError(f"Unknown method: {method}")
            except RuntimeError as e:
                print(f"RuntimeError in {method}: {e}")
                unstable = True
                break

            if not np.isfinite(out["loss"]) or not np.isfinite(out["grad_norm"]) or not np.isfinite(out["update_norm"]):
                unstable = True
                break

            step_records.append(
                StepRecord(
                    epoch=epoch,
                    step=global_step,
                    wall_time=time.time() - t0,
                    train_loss=out["loss"],
                    train_acc=out["acc"],
                    grad_norm=out["grad_norm"],
                    update_norm=out["update_norm"],
                    param_norm=out["param_norm"],
                    gate_mean=gate_mean,
                    gate_sat=gate_sat,
                    damping_mean=out["damping_mean"],
                    damping_min=out["damping_min"],
                    damping_max=out["damping_max"],
                )
            )

        if unstable:
            break

        test_loss, test_acc = evaluate_model(model, test_loader, device)
        best_test_acc = max(best_test_acc, test_acc)
        print(
            f"{task_name} | {method} | seed={seed} | epoch={epoch} | "
            f"test_loss={test_loss:.4f} | test_acc={test_acc:.4f}"
        )

    total_wall = time.time() - t0
    test_loss, test_acc = evaluate_model(model, test_loader, device)

    summary = RunSummary(
        task=task_name,
        method=method,
        seed=seed,
        final_test_loss=test_loss,
        final_test_acc=test_acc,
        best_test_acc=best_test_acc,
        total_wall_time=total_wall,
        unstable=unstable,
        hidden_weight_norm=float(model.fc1.weight.data.norm().item()),
        output_weight_norm=float(model.fc2.weight.data.norm().item()),
    )

    return model, pd.DataFrame([asdict(r) for r in step_records]), summary

"""
This cell makes the core comparison plots:
- training loss vs step
- training accuracy vs step
- training accuracy vs wall-clock time
- gradient norm vs step
- update norm vs step
- gate and damping traces for the gated Newton method"""

def plot_metric(df: pd.DataFrame, y: str, title: str, x: str = "step"):
    plt.figure(figsize=(7, 4))
    for method, sub in df.groupby("method"):
        sub = sub.sort_values(x)
        plt.plot(sub[x], sub[y], label=method)
    plt.xlabel(x)
    plt.ylabel(y)
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_gated_only(df: pd.DataFrame):
    sub = df[df["method"] == "gated_damped_newton_cg"].copy()
    if sub.empty:
        print("No gated_damped_newton_cg rows found.")
        return

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    axes[0].plot(sub["step"], sub["gate_mean"])
    axes[0].set_title("Gate mean vs step")
    axes[0].set_xlabel("step")
    axes[0].set_ylabel("gate_mean")

    axes[1].plot(sub["step"], sub["gate_sat"])
    axes[1].set_title("Gate saturation vs step")
    axes[1].set_xlabel("step")
    axes[1].set_ylabel("gate_sat")

    axes[2].plot(sub["step"], sub["damping_mean"], label="mean")
    axes[2].plot(sub["step"], sub["damping_min"], label="min")
    axes[2].plot(sub["step"], sub["damping_max"], label="max")
    axes[2].set_title("Effective damping vs step")
    axes[2].set_xlabel("step")
    axes[2].legend()

    plt.tight_layout()
    plt.show()

"""
This cell sets the CIFAR-100 experiment configuration."""

cifar_cfg = {
    "batch_size": 256,
    "train_subset": 8000,   # set to None for full training set
    "test_subset": 2000,    # set to None for full test set
    "hidden_dim": 256,
    "epochs": 6,
    "lr_sgd": 0.05,
    "lr_newton": 0.1,
    "momentum": 0.9,
    "base_damping": 10.0,
    "alpha": 0.9,
    "g_max": 1.0,
    "kappa": 2.0,
    "max_cg_iter": 6,
    "cg_tol": 1e-3,
    "seeds": [0, 1],
    "methods": ["sgd", "sgd_momentum", "damped_newton_cg", "gated_damped_newton_cg"],
}

"""
This cell runs the four-method optimiser comparison on CIFAR-100 and stores all stepwise diagnostics."""

cifar_train_loader, cifar_test_loader, cifar_input_dim, cifar_output_dim = make_cifar100_loaders(
    batch_size=cifar_cfg["batch_size"],
    train_subset=cifar_cfg["train_subset"],
    test_subset=cifar_cfg["test_subset"],
)

cifar_frames = []
cifar_summaries = []
cifar_models = {}

for seed in cifar_cfg["seeds"]:
    for method in cifar_cfg["methods"]:
        lr_use = cifar_cfg["lr_newton"] if "newton" in method else cifar_cfg["lr_sgd"]
        model, frame, summary = train_one_run(
            task_name="cifar100",
            method=method,
            train_loader=cifar_train_loader,
            test_loader=cifar_test_loader,
            input_dim=cifar_input_dim,
            output_dim=cifar_output_dim,
            seed=seed,
            hidden_dim=cifar_cfg["hidden_dim"],
            epochs=cifar_cfg["epochs"],
            lr=lr_use,
            momentum=cifar_cfg["momentum"],
            base_damping=cifar_cfg["base_damping"],
            alpha=cifar_cfg["alpha"],
            g_max=cifar_cfg["g_max"],
            kappa=cifar_cfg["kappa"],
            max_cg_iter=cifar_cfg["max_cg_iter"],
            cg_tol=cifar_cfg["cg_tol"],
        )
        frame["task"] = "cifar100"
        frame["method"] = method
        frame["seed"] = seed
        cifar_frames.append(frame)
        cifar_summaries.append(asdict(summary))
        cifar_models[(method, seed)] = model

cifar_steps = pd.concat(cifar_frames, ignore_index=True)
cifar_summary = pd.DataFrame(cifar_summaries)
display(cifar_summary)

"""

This cell plots the main optimiser-dynamics diagnostics for CIFAR-100."""

plot_metric(cifar_steps, y="train_loss", title="CIFAR-100: train loss vs step")
plot_metric(cifar_steps, y="train_acc", title="CIFAR-100: train accuracy vs step")
plot_metric(cifar_steps, y="train_acc", title="CIFAR-100: train accuracy vs wall-clock time", x="wall_time")
plot_metric(cifar_steps, y="grad_norm", title="CIFAR-100: gradient norm vs step")
plot_metric(cifar_steps, y="update_norm", title="CIFAR-100: update norm vs step")
plot_gated_only(cifar_steps)

"""
This cell loads Haxby, prepares grouped cross-validation by run/chunk, and sets the shared optimiser comparison."""

X_haxby, y_haxby, groups_haxby, haxby_encoder = load_haxby_arrays(
    subject_id=2,
    use_vt_mask=True,
    keep_scrambledpix=False,
    pca_components=128,
)

haxby_cfg = {
    "batch_size": 128,
    "hidden_dim": 256,
    "epochs": 12,
    "lr_sgd": 0.05,
    "lr_newton": 1.0,
    "momentum": 0.9,
    "base_damping": 1.0,
    "alpha": 0.9,
    "g_max": 1.0,
    "kappa": 2.0,
    "max_cg_iter": 8,
    "cg_tol": 1e-4,
    "seeds": [0, 1],
    "methods": ["sgd", "sgd_momentum", "damped_newton_cg", "gated_damped_newton_cg"],
    "n_splits": 5,
}

splitter = GroupKFold(n_splits=haxby_cfg["n_splits"])
print("Haxby classes:", list(haxby_encoder.classes_))
print("Haxby X shape:", X_haxby.shape)

"""
This cell runs the same four-method comparison on Haxby using grouped train/test splits."""

haxby_frames = []
haxby_summaries = []

for fold_idx, (train_idx, test_idx) in enumerate(splitter.split(X_haxby, y_haxby, groups=groups_haxby), start=1):
    X_train, y_train = X_haxby[train_idx], y_haxby[train_idx]
    X_test, y_test = X_haxby[test_idx], y_haxby[test_idx]
    train_loader, test_loader = make_array_loaders(
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
        batch_size=haxby_cfg["batch_size"],
    )

    for seed in haxby_cfg["seeds"]:
        for method in haxby_cfg["methods"]:
            lr_use = haxby_cfg["lr_newton"] if "newton" in method else haxby_cfg["lr_sgd"]
            model, frame, summary = train_one_run(
                task_name="haxby",
                method=method,
                train_loader=train_loader,
                test_loader=test_loader,
                input_dim=X_train.shape[1],
                output_dim=int(y_haxby.max() + 1),
                seed=seed,
                hidden_dim=haxby_cfg["hidden_dim"],
                epochs=haxby_cfg["epochs"],
                lr=lr_use,
                momentum=haxby_cfg["momentum"],
                base_damping=haxby_cfg["base_damping"],
                alpha=haxby_cfg["alpha"],
                g_max=haxby_cfg["g_max"],
                kappa=haxby_cfg["kappa"],
                max_cg_iter=haxby_cfg["max_cg_iter"],
                cg_tol=haxby_cfg["cg_tol"],
            )
            frame["task"] = "haxby"
            frame["method"] = method
            frame["seed"] = seed
            frame["fold"] = fold_idx
            haxby_frames.append(frame)

            row = asdict(summary)
            row["fold"] = fold_idx
            haxby_summaries.append(row)

haxby_steps = pd.concat(haxby_frames, ignore_index=True)
haxby_summary = pd.DataFrame(haxby_summaries)
display(haxby_summary.head())

"""
This cell aggregates Haxby results across folds and plots the same optimiser-dynamics diagnostics used for CIFAR-100."""

haxby_rule_summary = (
    haxby_summary
    .groupby(["method", "seed"], as_index=False)
    .agg(
        mean_final_test_loss=("final_test_loss", "mean"),
        mean_final_test_acc=("final_test_acc", "mean"),
        mean_best_test_acc=("best_test_acc", "mean"),
        mean_wall_time=("total_wall_time", "mean"),
        unstable_fraction=("unstable", "mean"),
    )
)

display(haxby_rule_summary)

plot_metric(haxby_steps, y="train_loss", title="Haxby: train loss vs step")
plot_metric(haxby_steps, y="train_acc", title="Haxby: train accuracy vs step")
plot_metric(haxby_steps, y="train_acc", title="Haxby: train accuracy vs wall-clock time", x="wall_time")
plot_metric(haxby_steps, y="grad_norm", title="Haxby: gradient norm vs step")
plot_metric(haxby_steps, y="update_norm", title="Haxby: update norm vs step")
plot_gated_only(haxby_steps)

"""
At this point I was pretty pessimistic so I wanted to verify we weren't doing much, e.g. checking RSAs."""

from scipy.stats import spearmanr
from scipy.spatial.distance import pdist, squareform
import copy


def upper_tri_vec(M: np.ndarray) -> np.ndarray:
    idx = np.triu_indices_from(M, k=1)
    return M[idx]


def cosine_similarity_vec(a: np.ndarray, b: np.ndarray, eps: float = 1e-12) -> float:
    na = np.linalg.norm(a)
    nb = np.linalg.norm(b)
    if na < eps or nb < eps:
        return np.nan
    return float(np.dot(a, b) / (na * nb))


def average_patterns_by_label(X: np.ndarray, y: np.ndarray):
    classes = np.unique(y)
    X_avg = []
    kept = []
    for c in classes:
        mask = (y == c)
        if mask.sum() > 0:
            X_avg.append(X[mask].mean(axis=0))
            kept.append(int(c))
    return np.stack(X_avg, axis=0), np.array(kept, dtype=int)


def rdm_from_patterns(X: np.ndarray, metric: str = "correlation") -> np.ndarray:
    # X: [n_conditions, n_features]
    return squareform(pdist(X, metric=metric))


def rsa_between_rdms(brain_rdm: np.ndarray, model_rdm: np.ndarray):
    b = upper_tri_vec(brain_rdm)
    m = upper_tri_vec(model_rdm)

    spear = spearmanr(b, m).statistic
    cos = cosine_similarity_vec(b, m)

    return {
        "rsa_spearman": float(spear) if np.isfinite(spear) else np.nan,
        "rsa_cosine": float(cos) if np.isfinite(cos) else np.nan,
    }


@torch.no_grad()
def extract_hidden_features(model, X: np.ndarray, batch_size: int = 256, device: torch.device = device):
    model.eval()
    feats = []
    n = X.shape[0]
    for start in range(0, n, batch_size):
        xb = torch.tensor(X[start:start + batch_size], dtype=torch.float32, device=device)
        _, hidden = model(xb)
        feats.append(hidden.detach().cpu().numpy())
    return np.concatenate(feats, axis=0)

@torch.no_grad()
def evaluate_array_model(model, loader, device):
    model.eval()
    total = 0
    correct = 0
    total_loss = 0.0

    for xb, yb in loader:
        xb = xb.to(device)
        yb = yb.to(device)

        logits, _ = model(xb)
        loss = F.cross_entropy(logits, yb, reduction="sum")

        total_loss += float(loss.item())
        correct += int((logits.argmax(dim=1) == yb).sum().item())
        total += yb.size(0)

    return total_loss / max(total, 1), correct / max(total, 1)

def train_one_array_run_return_model(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    rule: str,
    seed: int,
    device: torch.device,
    hidden_dim: int = 256,
    epochs: int = 30,
    batch_size: int = 64,
    lr: float = 0.05,
    momentum: float = 0.9,
    lr_newton: float = 0.1,
    base_damping: float = 10.0,
    max_cg_iter: int = 6,
    cg_tol: float = 1e-3,
    alpha_gate: float = 0.9,
    g_max: float = 1.0,
    kappa: float = 1.0,
):
    set_seed(seed)

    input_dim = X_train.shape[1]
    num_classes = int(max(y_train.max(), y_test.max()) + 1)

    # SmallMLP in the notebook uses output_dim, not num_classes
    model = SmallMLP(
        input_dim=input_dim,
        hidden_dim=hidden_dim,
        output_dim=num_classes,
    ).to(device)

    train_loader, test_loader = make_array_loaders(
        X_train, y_train, X_test, y_test, batch_size=batch_size
    )

    if rule == "sgd":
        optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.0)
    elif rule == "momentum":
        optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=momentum)
    else:
        optimizer = None

    gate_state = {
        "prev_hidden_mean": None,
        "gate_trace": None,
    }

    best_test_acc = 0.0
    last_info = None

    for epoch in range(epochs):
        model.train()

        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            if rule in {"sgd", "momentum"}:
                optimizer.zero_grad(set_to_none=True)
                logits, hidden = model(xb)
                loss = F.cross_entropy(logits, yb)
                loss.backward()
                optimizer.step()

                with torch.no_grad():
                    batch_acc = float((logits.argmax(dim=1) == yb).float().mean().item())
                    grad_sq = 0.0
                    for p in model.parameters():
                        if p.grad is not None:
                            grad_sq += float((p.grad.detach() ** 2).sum().item())
                    grad_norm = math.sqrt(max(grad_sq, 0.0))
                    param_norm = float(parameters_to_vector([p.detach() for p in model.parameters()]).norm().item())

                last_info = {
                    "loss": float(loss.item()),
                    "acc": batch_acc,
                    "grad_norm": grad_norm,
                    "update_norm": np.nan,
                    "param_norm": param_norm,
                    "damping_mean": np.nan,
                    "damping_min": np.nan,
                    "damping_max": np.nan,
                    "hidden": hidden.detach(),
                    "cg_status": "first_order",
                    "cg_iters": 0,
                    "step_scale": 1.0,
                }

            elif rule in {"newton", "gated_newton"}:
                with torch.no_grad():
                    xb_flat = prepare_mlp_input(xb)
                    _, hidden0 = model(xb_flat)
                    hidden_mean = hidden0.mean(dim=0)

                    if gate_state["prev_hidden_mean"] is None:
                        gate_state["prev_hidden_mean"] = hidden_mean.clone()
                        gate_state["gate_trace"] = torch.zeros_like(hidden_mean)

                    delta = hidden_mean - gate_state["prev_hidden_mean"]
                    pos_delta = torch.relu(delta)
                    gate_state["gate_trace"] = alpha_gate * gate_state["gate_trace"] + (1.0 - alpha_gate) * pos_delta
                    hidden_gate = torch.clamp(gate_state["gate_trace"], 0.0, g_max)
                    gate_state["prev_hidden_mean"] = hidden_mean.clone()

                hidden_gate_for_step = None if rule == "newton" else hidden_gate

                last_info = newton_cg_step(
                    model=model,
                    xb=xb,
                    yb=yb,
                    lr=lr_newton,
                    base_damping=base_damping,
                    max_cg_iter=max_cg_iter,
                    cg_tol=cg_tol,
                    hidden_gate=hidden_gate_for_step,
                    kappa=kappa,
                )

            else:
                raise ValueError(f"Unknown rule: {rule}")

        test_loss, test_acc = evaluate_array_model(model, test_loader, device)
        best_test_acc = max(best_test_acc, test_acc)

    train_loss, train_acc = evaluate_array_model(model, train_loader, device)
    test_loss, test_acc = evaluate_array_model(model, test_loader, device)

    metrics = {
        "dataset": "haxby",
        "rule": rule,
        "seed": seed,
        "final_test_accuracy": float(test_acc),
        "best_test_accuracy": float(best_test_acc),
        "train_accuracy": float(train_acc),
        "final_train_loss": float(train_loss),
        "final_test_loss": float(test_loss),
    }

    if last_info is not None:
        metrics.update({
            "last_grad_norm": float(last_info["grad_norm"]) if np.isfinite(last_info["grad_norm"]) else np.nan,
            "last_update_norm": float(last_info["update_norm"]) if np.isfinite(last_info["update_norm"]) else np.nan,
            "last_param_norm": float(last_info["param_norm"]) if np.isfinite(last_info["param_norm"]) else np.nan,
            "last_damping_mean": float(last_info["damping_mean"]) if np.isfinite(last_info["damping_mean"]) else np.nan,
            "last_damping_min": float(last_info["damping_min"]) if np.isfinite(last_info["damping_min"]) else np.nan,
            "last_damping_max": float(last_info["damping_max"]) if np.isfinite(last_info["damping_max"]) else np.nan,
            "last_cg_status": last_info["cg_status"],
            "last_cg_iters": int(last_info["cg_iters"]),
            "last_step_scale": float(last_info["step_scale"]),
        })

    return metrics, copy.deepcopy(model).cpu()

def run_haxby_cv_with_rsa(
    X: np.ndarray,
    y: np.ndarray,
    groups: np.ndarray,
    rules: list[str],
    seeds: list[int],
    n_splits: int = 5,
    hidden_dim: int = 256,
    epochs: int = 30,
    batch_size: int = 64,
    lr: float = 0.05,
    momentum: float = 0.9,
    lr_newton: float = 0.1,
    base_damping: float = 10.0,
    max_cg_iter: int = 6,
    cg_tol: float = 1e-3,
    alpha_gate: float = 0.9,
    g_max: float = 1.0,
    kappa: float = 1.0,
    pca_components: int = 128,
):
    splitter = GroupKFold(n_splits=n_splits)
    rows = []

    for fold_idx, (train_idx, test_idx) in enumerate(splitter.split(X, y, groups=groups), start=1):
        X_train_raw = X[train_idx]
        X_test_raw = X[test_idx]
        y_train = y[train_idx]
        y_test = y[test_idx]

        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train_raw)
        X_test_scaled = scaler.transform(X_test_raw)

        n_comp = min(pca_components, X_train_scaled.shape[0] - 1, X_train_scaled.shape[1])
        if n_comp >= 2:
            pca = PCA(n_components=n_comp, random_state=0)
            X_train = pca.fit_transform(X_train_scaled).astype(np.float32)
            X_test = pca.transform(X_test_scaled).astype(np.float32)
        else:
            pca = None
            X_train = X_train_scaled.astype(np.float32)
            X_test = X_test_scaled.astype(np.float32)

        # Brain-side RDM on held-out test fold, using raw voxel patterns averaged by class
        Xb_avg, kept_classes_brain = average_patterns_by_label(X_test_raw, y_test)
        brain_rdm = rdm_from_patterns(Xb_avg, metric="correlation")

        print(f"\nFold {fold_idx}: train={len(train_idx)}, test={len(test_idx)}, input_dim={X_train.shape[1]}")

        for rule in rules:
            for seed in seeds:
                metrics, model_cpu = train_one_array_run_return_model(
                    X_train=X_train,
                    y_train=y_train,
                    X_test=X_test,
                    y_test=y_test,
                    rule=rule,
                    seed=seed,
                    device=device,
                    hidden_dim=hidden_dim,
                    epochs=epochs,
                    batch_size=batch_size,
                    lr=lr,
                    momentum=momentum,
                    lr_newton=lr_newton,
                    base_damping=base_damping,
                    max_cg_iter=max_cg_iter,
                    cg_tol=cg_tol,
                    alpha_gate=alpha_gate,
                    g_max=g_max,
                    kappa=kappa,
                )

                # Model-side RDM from hidden activations on the same held-out stimuli
                hidden_test = extract_hidden_features(model_cpu.to(device), X_test, batch_size=batch_size, device=device)
                Xm_avg, kept_classes_model = average_patterns_by_label(hidden_test, y_test)

                # Align class order explicitly
                common = np.intersect1d(kept_classes_brain, kept_classes_model)
                if len(common) < 3:
                    rsa_stats = {"rsa_spearman": np.nan, "rsa_cosine": np.nan}
                else:
                    Xb_common = np.stack([Xb_avg[np.where(kept_classes_brain == c)[0][0]] for c in common], axis=0)
                    Xm_common = np.stack([Xm_avg[np.where(kept_classes_model == c)[0][0]] for c in common], axis=0)

                    brain_rdm_common = rdm_from_patterns(Xb_common, metric="correlation")
                    model_rdm_common = rdm_from_patterns(Xm_common, metric="correlation")
                    rsa_stats = rsa_between_rdms(brain_rdm_common, model_rdm_common)

                row = dict(metrics)
                row.update({
                    "fold": fold_idx,
                    "n_train": len(train_idx),
                    "n_test": len(test_idx),
                    "rsa_spearman": rsa_stats["rsa_spearman"],
                    "rsa_cosine": rsa_stats["rsa_cosine"],
                })
                rows.append(row)

                print(
                    f"rule={rule:13s} seed={seed} "
                    f"acc={row['final_test_accuracy']:.4f} "
                    f"rsa_s={row['rsa_spearman']:.4f} "
                    f"rsa_c={row['rsa_cosine']:.4f}"
                )

    return pd.DataFrame(rows)

haxby_rules = ["sgd", "momentum", "newton", "gated_newton"]
haxby_seeds = [0, 1, 2]

haxby_rsa_results = run_haxby_cv_with_rsa(
    X=X_haxby,
    y=y_haxby,
    groups=groups_haxby,
    rules=haxby_rules,
    seeds=haxby_seeds,
    n_splits=5,
    hidden_dim=256,
    epochs=30,
    batch_size=64,
    lr=0.05,
    momentum=0.9,
    lr_newton=0.1,
    base_damping=10.0,
    max_cg_iter=6,
    cg_tol=1e-3,
    alpha_gate=0.9,
    g_max=1.0,
    kappa=1.0,
    pca_components=128,
)

haxby_rsa_results.head()

haxby_rsa_summary = (
    haxby_rsa_results
    .groupby("rule", as_index=False)
    .agg(
        mean_accuracy=("final_test_accuracy", "mean"),
        std_accuracy=("final_test_accuracy", "std"),
        mean_rsa_spearman=("rsa_spearman", "mean"),
        std_rsa_spearman=("rsa_spearman", "std"),
        mean_rsa_cosine=("rsa_cosine", "mean"),
        std_rsa_cosine=("rsa_cosine", "std"),
    )
    .sort_values("mean_rsa_spearman", ascending=False)
    .reset_index(drop=True)
)

display(haxby_rsa_summary)

haxby_rsa_summary = (
    haxby_rsa_results
    .groupby("rule", as_index=False)
    .agg(
        mean_accuracy=("final_test_accuracy", "mean"),
        std_accuracy=("final_test_accuracy", "std"),
        mean_rsa_spearman=("rsa_spearman", "mean"),
        std_rsa_spearman=("rsa_spearman", "std"),
        mean_rsa_cosine=("rsa_cosine", "mean"),
        std_rsa_cosine=("rsa_cosine", "std"),
    )
    .sort_values("mean_rsa_spearman", ascending=False)
    .reset_index(drop=True)
)

display(haxby_rsa_summary)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].bar(haxby_rsa_summary["rule"], haxby_rsa_summary["mean_accuracy"])
axes[0].set_title("Haxby accuracy by optimiser")
axes[0].set_ylabel("Mean CV accuracy")
axes[0].tick_params(axis="x", rotation=30)

axes[1].bar(haxby_rsa_summary["rule"], haxby_rsa_summary["mean_rsa_spearman"])
axes[1].set_title("Brain-model RSA by optimiser")
axes[1].set_ylabel("Mean Spearman RDM similarity")
axes[1].tick_params(axis="x", rotation=30)

plt.tight_layout()
plt.show()

