# -*- coding: utf-8 -*-
"""gatewithstablewindow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQ6AE-5EkKHcMOz3MfBS8Eg_Xl2GUmoM

# Tail-length stress test for accelerometer-gated Hebbian learning

This notebook implements the tail-length stress test we discuss, because we wanted to check the stationary-duration-control idea, to see whether it actually works out in practice - then hopefully we see an example of a win for the accelerometer! It turns out it kind of does, but only in making us less confident in wrong answers (which is at least a probabilistic win? I'm not sure to be honest. I need to think more about what this means intuitively.)

The task is designed so that:
- the label is determined by an **early onset-order signal**
- the **late tail is shared across classes**
- the shared tail length is varied over a sweep

The methods compared are:
- vanilla Hebbian-Oja
- magnitude-gated Hebbian-Oja
- accelerometer-gated Hebbian-Oja
- backpropagation

The notebook reports:
- test accuracy
- test NLL
- test Brier score
- test ROC-AUC
- mean confidence
- hidden / readout / gradient norms
- gate mean and saturation
- hidden-weight diagnostics
- **phase-separated Hebbian-drive norms**:
  - onset drive
  - tail drive
  - tail/onset ratio

Anyways, some more details are here:

### Input space

Each example is a finite sequence of length $T$ of low-dimensional feature vectors. Equivalently, a trial may be represented as a matrix in $\mathbb{R}^{T \times d}$, where $d$ is the frame-level feature dimension. For learning with the MLP, this sequence is flattened into a vector in $\mathbb{R}^{Td}$ before being passed to the model.

Two latent feature templates, denoted $u_A$ and $u_B$, are sampled once per dataset. On each trial, the observed sequence is generated by combining these templates with time-dependent amplitudes:
$$
x_t = r_A(t)u_A + r_B(t)u_B + \varepsilon_t,
$$
where $r_A(t)$ and $r_B(t)$ are ramp functions controlling when each latent feature appears, and $\varepsilon_t$ is additive noise.

### Output / prediction target

The target is a binary class label determined by **which latent feature appears first**:
- **Class 0:** feature $A$ emerges before feature $B$.
- **Class 1:** feature $B$ emerges before feature $A$.

### Informative and non-informative phases

The sequence is deliberately partitioned into two conceptually distinct regimes.

#### 1. Informative onset regime
Early in the sequence, the order in which the two latent features emerge contains the class information. This is the part of the input from which a useful learner should extract signal.

#### 2. Shared stationary tail
Late in the sequence, both latent features are fully present and the sequence enters a shared, approximately stationary regime that is intentionally similar across classes. This late portion is not intended to improve classification. Instead, it functions as a structured distractor for local learning rules that continue integrating correlations over time.

The central manipulation in the notebook is the **tail-length sweep**
$$
L \in \{0,5,10,20,40,80\},
$$
which controls the duration of this shared stationary tail.

### Model class

All methods are evaluated in the same one-hidden-layer multilayer perceptron. The model consists of:
- an input layer receiving the flattened sequence,
- a hidden layer,
- a supervised linear readout layer.

The output of the network is a two-class logit vector. Predictive performance is measured on held-out data.
"""

import math
import random
import time
from dataclasses import dataclass, asdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def make_ramp(T, start, width, max_amp=1.0):
    r = np.zeros(T, dtype=np.float32)
    end = min(T, start + width)
    if end > start:
        r[start:end] = np.linspace(0.0, max_amp, end - start, endpoint=False, dtype=np.float32)
    if end < T:
        r[end:] = max_amp
    return r


def make_false_start(T, start, width, amp):
    r = np.zeros(T, dtype=np.float32)
    end = min(T, start + width)
    if end > start:
        r[start:end] = np.linspace(0.0, amp, end - start, endpoint=False, dtype=np.float32)
    return r


def generate_order_of_onset_dataset(
    n_samples=4000,
    T=30,
    frame_dim=20,
    noise_std=0.18,
    onset_gap=6,
    ramp_width=4,
    jitter=1,
    false_start_prob=0.15,
    false_start_amp=0.08,
    false_start_width=2,
    tail_length=8,
    overlap=0.55,
    seed=0,
):
    rng = np.random.default_rng(seed)

    uA = rng.normal(size=frame_dim).astype(np.float32)
    uB = rng.normal(size=frame_dim).astype(np.float32)
    uB = overlap * uA + (1.0 - overlap) * uB

    uA /= np.linalg.norm(uA) + 1e-8
    uB /= np.linalg.norm(uB) + 1e-8

    X = np.zeros((n_samples, T, frame_dim), dtype=np.float32)
    y = np.zeros(n_samples, dtype=np.int64)

    latest_start = T - ramp_width - max(tail_length, 2) - 1
    latest_start = max(latest_start, 5)

    for i in range(n_samples):
        cls = rng.integers(0, 2)
        y[i] = cls

        base_start = rng.integers(5, latest_start + 1)

        if cls == 0:
            start_A = base_start
            start_B = base_start + onset_gap + rng.integers(-jitter, jitter + 1)
        else:
            start_B = base_start
            start_A = base_start + onset_gap + rng.integers(-jitter, jitter + 1)

        start_A = max(1, min(T - ramp_width - tail_length - 1, start_A))
        start_B = max(1, min(T - ramp_width - tail_length - 1, start_B))

        rA = make_ramp(T, start_A, ramp_width, max_amp=1.0)
        rB = make_ramp(T, start_B, ramp_width, max_amp=1.0)

        if tail_length > 0:
            tail_start = max(0, T - tail_length)
            rA[tail_start:] = 1.0
            rB[tail_start:] = 1.0

        if rng.random() < false_start_prob:
            fs_max = max(2, min(start_A, start_B))
            fs_start = rng.integers(1, fs_max)
            if cls == 0:
                rB += make_false_start(T, fs_start, false_start_width, false_start_amp)
            else:
                rA += make_false_start(T, fs_start, false_start_width, false_start_amp)

        seq = np.outer(rA, uA) + np.outer(rB, uB)
        seq += rng.normal(scale=noise_std, size=seq.shape).astype(np.float32)
        X[i] = seq

    return X, y, uA, uB


def build_loaders(
    tail_length,
    n_train=3000,
    n_test=1000,
    batch_size=128,
    seed=42,
    T=30,
    frame_dim=20,
    noise_std=0.18,
    onset_gap=6,
    ramp_width=4,
    jitter=1,
    false_start_prob=0.15,
    false_start_amp=0.08,
    false_start_width=2,
    overlap=0.55,
):
    X_train, y_train, uA, uB = generate_order_of_onset_dataset(
        n_samples=n_train, T=T, frame_dim=frame_dim, noise_std=noise_std,
        onset_gap=onset_gap, ramp_width=ramp_width, jitter=jitter,
        false_start_prob=false_start_prob, false_start_amp=false_start_amp,
        false_start_width=false_start_width, tail_length=tail_length,
        overlap=overlap, seed=seed
    )
    X_test, y_test, _, _ = generate_order_of_onset_dataset(
        n_samples=n_test, T=T, frame_dim=frame_dim, noise_std=noise_std,
        onset_gap=onset_gap, ramp_width=ramp_width, jitter=jitter,
        false_start_prob=false_start_prob, false_start_amp=false_start_amp,
        false_start_width=false_start_width, tail_length=tail_length,
        overlap=overlap, seed=seed + 1
    )

    X_train_flat = X_train.reshape(n_train, T * frame_dim)
    X_test_flat = X_test.reshape(n_test, T * frame_dim)

    scaler = StandardScaler()
    X_train_flat = scaler.fit_transform(X_train_flat).astype(np.float32)
    X_test_flat = scaler.transform(X_test_flat).astype(np.float32)

    train_ds = TensorDataset(
        torch.tensor(X_train_flat, dtype=torch.float32),
        torch.tensor(y_train, dtype=torch.long),
    )
    test_ds = TensorDataset(
        torch.tensor(X_test_flat, dtype=torch.float32),
        torch.tensor(y_test, dtype=torch.long),
    )

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)

    meta = {
        "T": T,
        "frame_dim": frame_dim,
        "input_dim": T * frame_dim,
        "num_classes": 2,
        "tail_length": tail_length,
        "X_train_seq": X_train,
        "X_test_seq": X_test,
        "y_train": y_train,
        "y_test": y_test,
        "uA": uA,
        "uB": uB,
    }
    return train_loader, test_loader, meta


def plot_sequence(seq, title=""):
    plt.figure(figsize=(10, 3))
    plt.imshow(seq.T, aspect="auto", origin="lower")
    plt.colorbar()
    plt.xlabel("time")
    plt.ylabel("feature")
    plt.title(title)
    plt.tight_layout()
    plt.show()


_, _, meta_demo = build_loaders(tail_length=20, n_train=100, n_test=20, batch_size=16, seed=0)
idx0 = np.where(meta_demo["y_train"] == 0)[0][0]
idx1 = np.where(meta_demo["y_train"] == 1)[0][0]
plot_sequence(meta_demo["X_train_seq"][idx0], "Class 0 sample")
plot_sequence(meta_demo["X_train_seq"][idx1], "Class 1 sample")


class OneHiddenMLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim, bias=False)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        nn.init.normal_(self.fc1.weight, mean=0.0, std=0.05)
        nn.init.normal_(self.fc2.weight, mean=0.0, std=0.05)
        nn.init.zeros_(self.fc2.bias)

    def forward(self, x):
        h = F.relu(self.fc1(x))
        logits = self.fc2(h)
        return logits, h


def weight_moments(W):
    w = W.reshape(-1)
    mu = float(w.mean())
    var = float(w.var())
    std = math.sqrt(var + 1e-12)
    skew = float(np.mean(((w - mu) / std) ** 3))
    kurt = float(np.mean(((w - mu) / std) ** 4) - 3.0)
    return var, skew, kurt


def mean_pairwise_cosine(W):
    row_norms = np.linalg.norm(W, axis=1, keepdims=True) + 1e-12
    Z = W / row_norms
    C = Z @ Z.T
    n = C.shape[0]
    idx = np.triu_indices(n, k=1)
    return float(C[idx].mean()) if len(idx[0]) > 0 else np.nan


def effective_rank(W):
    s = np.linalg.svd(W, compute_uv=False)
    s = np.maximum(s, 1e-12)
    p = s / s.sum()
    entropy = -np.sum(p * np.log(p))
    return float(np.exp(entropy))


def brier_score_binary(probs, y_true):
    return float(np.mean((probs - y_true) ** 2))


@torch.no_grad()


def evaluate_model(model, loader, device):
    model.eval()
    total = 0
    correct = 0
    total_loss = 0.0
    all_probs = []
    all_y = []

    for xb, yb in loader:
        xb = xb.to(device)
        yb = yb.to(device)
        logits, _ = model(xb)
        loss = F.cross_entropy(logits, yb, reduction="sum")
        probs = torch.softmax(logits, dim=1)
        p1 = probs[:, 1]

        total_loss += float(loss.item())
        correct += int((logits.argmax(dim=1) == yb).sum().item())
        total += yb.size(0)

        all_probs.append(p1.detach().cpu().numpy())
        all_y.append(yb.detach().cpu().numpy())

    all_probs = np.concatenate(all_probs)
    all_y = np.concatenate(all_y)
    try:
        auc = float(roc_auc_score(all_y, all_probs))
    except Exception:
        auc = np.nan

    return {
        "nll": total_loss / max(total, 1),
        "acc": correct / max(total, 1),
        "brier": brier_score_binary(all_probs, all_y),
        "auc": auc,
        "mean_confidence": float(np.mean(np.maximum(all_probs, 1 - all_probs))),
    }


@dataclass


class RunMetrics:
    rule: str
    seed: int
    tail_length: int
    final_test_acc: float
    final_test_nll: float
    final_test_brier: float
    final_test_auc: float
    final_test_confidence: float
    mean_grad_norm: float
    mean_readout_update_norm: float
    mean_hidden_update_norm: float
    mean_onset_drive_norm: float
    mean_tail_drive_norm: float
    mean_tail_onset_ratio: float
    mean_gate: float | None
    mean_gate_saturation: float | None
    mean_weight_var: float
    mean_weight_skew: float
    mean_weight_kurtosis: float
    mean_pairwise_cosine: float
    mean_effective_rank: float
    mean_wallclock: float


def extra_readout_refit(model, train_loader, steps=20, lr=5e-2, device=device):
    opt = torch.optim.SGD(model.fc2.parameters(), lr=lr, momentum=0.9)
    it = iter(train_loader)
    model.train()
    for _ in range(steps):
        try:
            xb, yb = next(it)
        except StopIteration:
            it = iter(train_loader)
            xb, yb = next(it)
        xb = xb.to(device)
        yb = yb.to(device)
        opt.zero_grad(set_to_none=True)
        logits, _ = model(xb)
        loss = F.cross_entropy(logits, yb)
        if not torch.isfinite(loss):
            continue
        loss.backward()
        opt.step()


def train_one_run(
    rule,
    seed,
    tail_length,
    train_loader,
    test_loader,
    input_dim,
    num_classes,
    T,
    frame_dim,
    hidden_dim=64,
    epochs=18,
    lr_hidden=2e-3,
    lr_out=5e-2,
    alpha_gate=0.9,
    g_max=1.0,
    lambda_oja=0.08,
    eval_every=3,
    diag_every=3,
    extra_readout_refit_steps=20,
    device=device,
):
    set_seed(seed)
    model = OneHiddenMLP(input_dim=input_dim, hidden_dim=hidden_dim, output_dim=num_classes).to(device)

    if rule == "backprop":
        optimizer = torch.optim.SGD(model.parameters(), lr=lr_out, momentum=0.9)
    else:
        optimizer = torch.optim.SGD(model.fc2.parameters(), lr=lr_out, momentum=0.9)

    prev_hidden_mean = torch.zeros(hidden_dim, device=device)
    gate_trace = torch.zeros(hidden_dim, device=device)

    history = []
    onset_steps = T - tail_length
    onset_dim = onset_steps * frame_dim

    for epoch in range(epochs):
        model.train()

        epoch_grad_norm = []
        epoch_readout_update_norm = []
        epoch_hidden_update_norm = []
        epoch_onset_drive = []
        epoch_tail_drive = []
        epoch_tail_onset_ratio = []
        epoch_gate = []
        epoch_gate_sat = []
        epoch_weight_var = []
        epoch_weight_skew = []
        epoch_weight_kurt = []
        epoch_pairwise_cos = []
        epoch_eff_rank = []

        t0 = time.time()
        valid_batches = 0

        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            fc1_before = model.fc1.weight.detach().clone()
            fc2_before_w = model.fc2.weight.detach().clone()
            fc2_before_b = model.fc2.bias.detach().clone()

            optimizer.zero_grad(set_to_none=True)
            logits, h = model(xb)
            loss = F.cross_entropy(logits, yb)
            if not torch.isfinite(loss):
                continue
            loss.backward()

            grad_sq = 0.0
            params = model.parameters() if rule == "backprop" else model.fc2.parameters()
            for p in params:
                if p.grad is not None and torch.isfinite(p.grad).all():
                    grad_sq += float((p.grad.detach() ** 2).sum().item())
            grad_norm = math.sqrt(max(grad_sq, 0.0))
            optimizer.step()

            with torch.no_grad():
                fc2_after_w = model.fc2.weight.detach()
                fc2_after_b = model.fc2.bias.detach()
                readout_update_norm = float(
                    torch.sqrt(
                        ((fc2_after_w - fc2_before_w) ** 2).sum()
                        + ((fc2_after_b - fc2_before_b) ** 2).sum()
                    ).item()
                )

                gate_mean = np.nan
                gate_sat = np.nan
                hidden_update_norm = np.nan
                onset_drive_norm = np.nan
                tail_drive_norm = np.nan
                tail_onset_ratio = np.nan

                if rule != "backprop":
                    hidden_mean = h.detach().mean(dim=0)

                    if rule == "hebbian":
                        gate = torch.ones_like(hidden_mean)
                    elif rule == "magnitude_gate":
                        gate_trace = alpha_gate * gate_trace + (1.0 - alpha_gate) * hidden_mean
                        gate = torch.clamp(gate_trace, 0.0, g_max)
                    elif rule == "accel_gate":
                        delta = hidden_mean - prev_hidden_mean
                        pos_delta = torch.relu(delta)
                        gate_trace = alpha_gate * gate_trace + (1.0 - alpha_gate) * pos_delta
                        gate = torch.clamp(gate_trace, 0.0, g_max)
                    else:
                        raise ValueError(f"Unknown rule: {rule}")

                    pre_total = xb.detach()
                    pre_onset = pre_total.clone()
                    pre_tail = pre_total.clone()
                    pre_onset[:, onset_dim:] = 0.0
                    pre_tail[:, :onset_dim] = 0.0
                    post = h.detach()

                    hebb_total = (post.T @ pre_total) / pre_total.shape[0]
                    hebb_onset = (post.T @ pre_onset) / pre_total.shape[0]
                    hebb_tail = (post.T @ pre_tail) / pre_total.shape[0]

                    post_sq = (post ** 2).mean(dim=0, keepdim=True).T
                    oja_term = lambda_oja * post_sq * model.fc1.weight

                    delta_w = lr_hidden * gate.unsqueeze(1) * (hebb_total - oja_term)
                    if not torch.isfinite(delta_w).all():
                        continue
                    model.fc1.weight.add_(delta_w)

                    onset_drive = lr_hidden * gate.unsqueeze(1) * hebb_onset
                    tail_drive = lr_hidden * gate.unsqueeze(1) * hebb_tail
                    onset_drive_norm = float(onset_drive.norm().item())
                    tail_drive_norm = float(tail_drive.norm().item())
                    tail_onset_ratio = float(tail_drive_norm / (onset_drive_norm + 1e-12))

                    prev_hidden_mean = hidden_mean.clone()
                    hidden_update_norm = float(delta_w.norm().item())
                    gate_mean = float(gate.mean().item())
                    gate_sat = float((gate >= g_max - 1e-8).float().mean().item())
                else:
                    fc1_after = model.fc1.weight.detach()
                    hidden_update_norm = float((fc1_after - fc1_before).norm().item())

                W = model.fc1.weight.detach().cpu().numpy()
                var, skew, kurt = weight_moments(W)
                pair_cos = mean_pairwise_cosine(W)
                eff_rank = effective_rank(W)

            valid_batches += 1
            epoch_grad_norm.append(grad_norm)
            epoch_readout_update_norm.append(readout_update_norm)
            epoch_hidden_update_norm.append(hidden_update_norm)
            epoch_onset_drive.append(onset_drive_norm)
            epoch_tail_drive.append(tail_drive_norm)
            epoch_tail_onset_ratio.append(tail_onset_ratio)
            epoch_gate.append(gate_mean)
            epoch_gate_sat.append(gate_sat)
            epoch_weight_var.append(var)
            epoch_weight_skew.append(skew)
            epoch_weight_kurt.append(kurt)
            epoch_pairwise_cos.append(pair_cos)
            epoch_eff_rank.append(eff_rank)

        if rule != "backprop" and extra_readout_refit_steps > 0:
            extra_readout_refit(model, train_loader, steps=extra_readout_refit_steps, lr=lr_out, device=device)

        elapsed = time.time() - t0
        if valid_batches == 0:
            break

        row = {
            "epoch": epoch + 1,
            "grad_norm": float(np.nanmean(epoch_grad_norm)),
            "readout_update_norm": float(np.nanmean(epoch_readout_update_norm)),
            "hidden_update_norm": float(np.nanmean(epoch_hidden_update_norm)),
            "onset_drive_norm": float(np.nanmean(epoch_onset_drive)),
            "tail_drive_norm": float(np.nanmean(epoch_tail_drive)),
            "tail_onset_ratio": float(np.nanmean(epoch_tail_onset_ratio)),
            "gate_mean": float(np.nanmean(epoch_gate)) if rule != "backprop" else np.nan,
            "gate_saturation": float(np.nanmean(epoch_gate_sat)) if rule != "backprop" else np.nan,
            "wallclock": elapsed,
        }

        if (epoch + 1) % eval_every == 0 or epoch == epochs - 1:
            train_eval = evaluate_model(model, train_loader, device)
            test_eval = evaluate_model(model, test_loader, device)
            row.update({
                "train_nll": train_eval["nll"],
                "test_nll": test_eval["nll"],
                "train_acc": train_eval["acc"],
                "test_acc": test_eval["acc"],
                "train_brier": train_eval["brier"],
                "test_brier": test_eval["brier"],
                "train_auc": train_eval["auc"],
                "test_auc": test_eval["auc"],
                "train_confidence": train_eval["mean_confidence"],
                "test_confidence": test_eval["mean_confidence"],
            })
        else:
            row.update({
                "train_nll": np.nan, "test_nll": np.nan,
                "train_acc": np.nan, "test_acc": np.nan,
                "train_brier": np.nan, "test_brier": np.nan,
                "train_auc": np.nan, "test_auc": np.nan,
                "train_confidence": np.nan, "test_confidence": np.nan,
            })

        if (epoch + 1) % diag_every == 0 or epoch == epochs - 1:
            row.update({
                "weight_var": float(np.nanmean(epoch_weight_var)),
                "weight_skew": float(np.nanmean(epoch_weight_skew)),
                "weight_kurtosis": float(np.nanmean(epoch_weight_kurt)),
                "pairwise_cosine": float(np.nanmean(epoch_pairwise_cos)),
                "effective_rank": float(np.nanmean(epoch_eff_rank)),
            })
        else:
            row.update({
                "weight_var": np.nan,
                "weight_skew": np.nan,
                "weight_kurtosis": np.nan,
                "pairwise_cosine": np.nan,
                "effective_rank": np.nan,
            })

        history.append(row)

    hist_df = pd.DataFrame(history)
    for col in [
        "train_nll", "test_nll", "train_acc", "test_acc",
        "train_brier", "test_brier", "train_auc", "test_auc",
        "train_confidence", "test_confidence",
        "weight_var", "weight_skew", "weight_kurtosis",
        "pairwise_cosine", "effective_rank"
    ]:
        hist_df[col] = hist_df[col].ffill()

    metrics = RunMetrics(
        rule=rule,
        seed=seed,
        tail_length=tail_length,
        final_test_acc=float(hist_df["test_acc"].iloc[-1]),
        final_test_nll=float(hist_df["test_nll"].iloc[-1]),
        final_test_brier=float(hist_df["test_brier"].iloc[-1]),
        final_test_auc=float(hist_df["test_auc"].iloc[-1]),
        final_test_confidence=float(hist_df["test_confidence"].iloc[-1]),
        mean_grad_norm=float(hist_df["grad_norm"].mean()),
        mean_readout_update_norm=float(hist_df["readout_update_norm"].mean()),
        mean_hidden_update_norm=float(hist_df["hidden_update_norm"].mean()),
        mean_onset_drive_norm=float(hist_df["onset_drive_norm"].mean()),
        mean_tail_drive_norm=float(hist_df["tail_drive_norm"].mean()),
        mean_tail_onset_ratio=float(hist_df["tail_onset_ratio"].mean()),
        mean_gate=float(hist_df["gate_mean"].mean()) if rule != "backprop" else np.nan,
        mean_gate_saturation=float(hist_df["gate_saturation"].mean()) if rule != "backprop" else np.nan,
        mean_weight_var=float(hist_df["weight_var"].mean()),
        mean_weight_skew=float(hist_df["weight_skew"].mean()),
        mean_weight_kurtosis=float(hist_df["weight_kurtosis"].mean()),
        mean_pairwise_cosine=float(hist_df["pairwise_cosine"].mean()),
        mean_effective_rank=float(hist_df["effective_rank"].mean()),
        mean_wallclock=float(hist_df["wallclock"].mean()),
    )
    return metrics, hist_df, model

tail_lengths = [0, 5, 10, 20, 40, 80]
rules = ["hebbian", "magnitude_gate", "accel_gate", "backprop"]
seeds = [0, 1, 2]

train_cfg = {
    "hidden_dim": 64,
    "epochs": 18,
    "lr_hidden": 2e-3,
    "lr_out": 5e-2,
    "alpha_gate": 0.9,
    "g_max": 1.0,
    "lambda_oja": 0.08,
    "eval_every": 3,
    "diag_every": 3,
    "extra_readout_refit_steps": 20,
}


def run_tail_length_sweep(
    tail_lengths,
    rules,
    seeds,
    train_cfg,
    n_train=3000,
    n_test=1000,
    batch_size=128,
    data_seed_base=100,
):
    all_metrics = []
    all_histories = {}

    for idx, L in enumerate(tail_lengths):
        print(f"\n=== Tail length {L} ({idx + 1}/{len(tail_lengths)}) ===")
        train_loader, test_loader, meta = build_loaders(
            tail_length=L,
            n_train=n_train,
            n_test=n_test,
            batch_size=batch_size,
            seed=data_seed_base + idx,
        )

        for rule in rules:
            for seed in seeds:
                metrics, hist_df, model = train_one_run(
                    rule=rule,
                    seed=seed,
                    tail_length=L,
                    train_loader=train_loader,
                    test_loader=test_loader,
                    input_dim=meta["input_dim"],
                    num_classes=meta["num_classes"],
                    T=meta["T"],
                    frame_dim=meta["frame_dim"],
                    hidden_dim=train_cfg["hidden_dim"],
                    epochs=train_cfg["epochs"],
                    lr_hidden=train_cfg["lr_hidden"],
                    lr_out=train_cfg["lr_out"],
                    alpha_gate=train_cfg["alpha_gate"],
                    g_max=train_cfg["g_max"],
                    lambda_oja=train_cfg["lambda_oja"],
                    eval_every=train_cfg["eval_every"],
                    diag_every=train_cfg["diag_every"],
                    extra_readout_refit_steps=train_cfg["extra_readout_refit_steps"],
                    device=device,
                )

                all_metrics.append(asdict(metrics))
                all_histories[(L, rule, seed)] = hist_df

                print(
                    f"L={L:3d} rule={rule:14s} seed={seed} "
                    f"acc={metrics.final_test_acc:.3f} "
                    f"auc={metrics.final_test_auc:.3f} "
                    f"nll={metrics.final_test_nll:.3f} "
                    f"tail/onset={metrics.mean_tail_onset_ratio:.3f}"
                )

    return pd.DataFrame(all_metrics), all_histories


results_df, all_histories = run_tail_length_sweep(
    tail_lengths=tail_lengths,
    rules=rules,
    seeds=seeds,
    train_cfg=train_cfg,
    n_train=3000,
    n_test=1000,
    batch_size=128,
    data_seed_base=100,
)

results_df.head()

summary_df = (
    results_df
    .groupby(["tail_length", "rule"], as_index=False)
    .agg(
        mean_test_acc=("final_test_acc", "mean"),
        std_test_acc=("final_test_acc", "std"),
        mean_test_nll=("final_test_nll", "mean"),
        mean_test_brier=("final_test_brier", "mean"),
        mean_test_auc=("final_test_auc", "mean"),
        mean_test_confidence=("final_test_confidence", "mean"),
        mean_grad_norm=("mean_grad_norm", "mean"),
        mean_readout_update_norm=("mean_readout_update_norm", "mean"),
        mean_hidden_update_norm=("mean_hidden_update_norm", "mean"),
        mean_onset_drive_norm=("mean_onset_drive_norm", "mean"),
        mean_tail_drive_norm=("mean_tail_drive_norm", "mean"),
        mean_tail_onset_ratio=("mean_tail_onset_ratio", "mean"),
        mean_gate=("mean_gate", "mean"),
        mean_gate_saturation=("mean_gate_saturation", "mean"),
        mean_weight_var=("mean_weight_var", "mean"),
        mean_weight_skew=("mean_weight_skew", "mean"),
        mean_weight_kurtosis=("mean_weight_kurtosis", "mean"),
        mean_pairwise_cosine=("mean_pairwise_cosine", "mean"),
        mean_effective_rank=("mean_effective_rank", "mean"),
        mean_wallclock=("mean_wallclock", "mean"),
    )
)
summary_df


def plot_metric_vs_tail(metric, ylabel):
    plt.figure(figsize=(7, 4))
    for rule in rules:
        tmp = summary_df[summary_df["rule"] == rule].sort_values("tail_length")
        plt.plot(tmp["tail_length"], tmp[metric], marker="o", label=rule)
    plt.xlabel("tail length")
    plt.ylabel(ylabel)
    plt.legend()
    plt.tight_layout()
    plt.show()

plot_metric_vs_tail("mean_test_acc", "test accuracy")
plot_metric_vs_tail("mean_test_auc", "test ROC-AUC")
plot_metric_vs_tail("mean_test_nll", "test NLL")
plot_metric_vs_tail("mean_test_brier", "test Brier score")
plot_metric_vs_tail("mean_test_confidence", "mean confidence")
plot_metric_vs_tail("mean_onset_drive_norm", "mean onset Hebbian-drive norm")
plot_metric_vs_tail("mean_tail_drive_norm", "mean tail Hebbian-drive norm")
plot_metric_vs_tail("mean_tail_onset_ratio", "mean tail/onset Hebbian-drive ratio")
plot_metric_vs_tail("mean_hidden_update_norm", "mean hidden update norm")
plot_metric_vs_tail("mean_gate", "mean gate")
plot_metric_vs_tail("mean_gate_saturation", "gate saturation")

pivot_acc = summary_df.pivot(index="tail_length", columns="rule", values="mean_test_acc")
pivot_auc = summary_df.pivot(index="tail_length", columns="rule", values="mean_test_auc")
pivot_nll = summary_df.pivot(index="tail_length", columns="rule", values="mean_test_nll")
pivot_brier = summary_df.pivot(index="tail_length", columns="rule", values="mean_test_brier")
pivot_ratio = summary_df.pivot(index="tail_length", columns="rule", values="mean_tail_onset_ratio")

comp = pd.DataFrame({"tail_length": pivot_acc.index.values})
comp["accel_minus_hebb_acc"] = pivot_acc["accel_gate"].values - pivot_acc["hebbian"].values
comp["accel_minus_hebb_auc"] = pivot_auc["accel_gate"].values - pivot_auc["hebbian"].values
comp["accel_minus_hebb_nll"] = pivot_nll["accel_gate"].values - pivot_nll["hebbian"].values
comp["accel_minus_hebb_brier"] = pivot_brier["accel_gate"].values - pivot_brier["hebbian"].values
comp["accel_minus_hebb_tailratio"] = pivot_ratio["accel_gate"].values - pivot_ratio["hebbian"].values

comp["accel_minus_mag_acc"] = pivot_acc["accel_gate"].values - pivot_acc["magnitude_gate"].values
comp["accel_minus_mag_auc"] = pivot_auc["accel_gate"].values - pivot_auc["magnitude_gate"].values
comp["accel_minus_mag_nll"] = pivot_nll["accel_gate"].values - pivot_nll["magnitude_gate"].values
comp["accel_minus_mag_brier"] = pivot_brier["accel_gate"].values - pivot_brier["magnitude_gate"].values
comp["accel_minus_mag_tailratio"] = pivot_ratio["accel_gate"].values - pivot_ratio["magnitude_gate"].values

comp

chosen_tail = 40


def plot_history(tail_length, quantity, ylabel):
    plt.figure(figsize=(7, 4))
    for rule in rules:
        curves = [all_histories[(tail_length, rule, s)][["epoch", quantity]].copy() for s in seeds]
        min_len = min(len(c) for c in curves)
        epochs = curves[0]["epoch"].values[:min_len]
        vals = np.stack([c[quantity].values[:min_len] for c in curves], axis=0)
        mean = np.nanmean(vals, axis=0)
        std = np.nanstd(vals, axis=0)
        plt.plot(epochs, mean, label=rule)
        plt.fill_between(epochs, mean - std, mean + std, alpha=0.15)
    plt.xlabel("epoch")
    plt.ylabel(ylabel)
    plt.title(f"{ylabel} at tail length = {tail_length}")
    plt.legend()
    plt.tight_layout()
    plt.show()

plot_history(chosen_tail, "test_acc", "test accuracy")
plot_history(chosen_tail, "test_nll", "test NLL")
plot_history(chosen_tail, "tail_onset_ratio", "tail/onset ratio")
plot_history(chosen_tail, "gate_mean", "gate mean")

