# -*- coding: utf-8 -*-
"""PCA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_N7L2igukhbFF7Ru2sAQhef4fyonJW2
"""

#Classic Oja learning makes a single Hebbian neuron learn the first principal
# component of the input. This code compares it to our accelerometer-gated
# Hebbian-Oja rule.

# Vanilla Oja is recovered by setting g(t) = 1.

from dataclasses import dataclass

import matplotlib.pyplot as plt
import numpy as np


SEED = 7
rng = np.random.default_rng(SEED)

plt.rcParams.update(
    {
        "figure.figsize": (8, 4.8),
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "font.size": 11,
    }
)


# %% Basic helpers
def relu(x):
    return np.maximum(0.0, x)


def unit_norm(w, eps=1e-12):
    return w / (np.linalg.norm(w) + eps)


def moving_average(x, window=200):
    x = np.asarray(x)
    if window <= 1:
        return x
    kernel = np.ones(window) / window
    return np.convolve(x, kernel, mode="same")


def make_covariance(d=8, eigvals=None, seed=0):
    """Create a covariance matrix with known eigenvectors/eigenvalues."""
    local_rng = np.random.default_rng(seed)
    if eigvals is None:
        eigvals = np.array([4.0, 2.0, 1.2, 0.8, 0.55, 0.35, 0.25, 0.15])
    eigvals = np.asarray(eigvals, dtype=float)
    if len(eigvals) != d:
        raise ValueError("len(eigvals) must equal d")

    q, _ = np.linalg.qr(local_rng.normal(size=(d, d)))
    if np.linalg.det(q) < 0:
        q[:, 0] *= -1
    cov = q @ np.diag(eigvals) @ q.T
    return cov, q, eigvals


def sample_gaussian(n, eigvecs, eigvals, rng):
    """Sample N(0, C), where C = eigvecs diag(eigvals) eigvecs.T."""
    z = rng.normal(size=(n, len(eigvals)))
    return z @ (eigvecs * np.sqrt(eigvals)).T


def minibatches(X, batch_size):
    for start in range(0, len(X), batch_size):
        xb = X[start : start + batch_size]
        if len(xb) == batch_size:
            yield xb


@dataclass
class RunResult:
    name: str
    steps: np.ndarray
    align: np.ndarray
    variance: np.ndarray
    weight_norm: np.ndarray
    gates: np.ndarray
    update_norms: np.ndarray
    mean_activity: np.ndarray
    final_w: np.ndarray


def run_single_relu_oja(
    X,
    C,
    v1,
    w0,
    rule="oja",
    eta_hid=0.08,
    alpha=0.90,
    g_max=2.0,
    lambda_oja=1.0,
    batch_size=64,
    normalize_after_update=False,
    log_every=25,
):
    """Run the project-style one-neuron ReLU Hebbian-Oja rule.

    rule="oja":        g(t) = 1
    rule="accel":      g(t) from positive changes in mean ReLU activity
    rule="magnitude":  control gate from mean ReLU activity level

    normalize_after_update is False by default because the MLP hidden-layer
    update in the project uses the Oja stabilizer rather than explicit
    Euclidean normalization. Set it to True if you want the normalized
    single-neuron variant from the theorem in the write-up.
    """
    w = w0.copy()
    a = 0.0
    m_prev = 0.0

    n_batches = len(X) // batch_size
    gates = np.zeros(n_batches)
    update_norms = np.zeros(n_batches)
    mean_activity = np.zeros(n_batches)
    steps, align, variance, weight_norm = [], [], [], []

    for t, xb in enumerate(minibatches(X, batch_size), start=1):
        z = xb @ w
        h = relu(z)
        m = float(h.mean())

        hebb = (h[:, None] * xb).mean(axis=0)
        post_second_moment = float((h**2).mean())

        if rule == "oja":
            g = 1.0
        elif rule == "accel":
            r = max(0.0, m - m_prev)
            a = alpha * a + (1.0 - alpha) * r
            g = min(g_max, a)
        elif rule == "magnitude":
            a = alpha * a + (1.0 - alpha) * m
            g = min(g_max, a)
        else:
            raise ValueError(f"Unknown rule: {rule}")

        raw_update = eta_hid * g * (hebb - lambda_oja * post_second_moment * w)
        w = w + raw_update
        if normalize_after_update:
            w = unit_norm(w)

        gates[t - 1] = g
        update_norms[t - 1] = np.linalg.norm(raw_update)
        mean_activity[t - 1] = m
        m_prev = m

        if t == 1 or t % log_every == 0 or t == n_batches:
            norm_w = np.linalg.norm(w)
            steps.append(t)
            align.append(abs(float(w @ v1)) / (norm_w * np.linalg.norm(v1)))
            variance.append(float(unit_norm(w) @ C @ unit_norm(w)))
            weight_norm.append(norm_w)

    return RunResult(
        name=rule,
        steps=np.array(steps),
        align=np.array(align),
        variance=np.array(variance),
        weight_norm=np.array(weight_norm),
        gates=gates,
        update_norms=update_norms,
        mean_activity=mean_activity,
        final_w=w,
    )


def plot_learning_curves(results, title, savepath=None):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.2))
    for res in results:
        axes[0].plot(res.steps, res.align, label=res.name)
        axes[1].plot(res.steps, res.variance, label=res.name)
        axes[2].plot(res.steps, res.weight_norm, label=res.name)

    axes[0].set_title("Alignment with first PC")
    axes[0].set_xlabel("Minibatch step")
    axes[0].set_ylabel(r"$|w^T v_1| / ||w||$")
    axes[0].set_ylim(0, 1.02)

    axes[1].set_title("Variance captured")
    axes[1].set_xlabel("Minibatch step")
    axes[1].set_ylabel(r"$\hat{w}^T C \hat{w}$")

    axes[2].set_title("Weight norm")
    axes[2].set_xlabel("Minibatch step")
    axes[2].set_ylabel(r"$||w||$")

    fig.suptitle(title, y=1.04)
    axes[0].legend()
    plt.tight_layout()
    if savepath is not None:
        plt.savefig(savepath, dpi=300, bbox_inches="tight")
    plt.show()


def plot_gate_and_updates(results, title, smooth=100):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.2))
    for res in results:
        axes[0].plot(moving_average(res.mean_activity, smooth), label=res.name)
        axes[1].plot(moving_average(res.gates, smooth), label=res.name)
        axes[2].plot(moving_average(res.update_norms, smooth), label=res.name)

    axes[0].set_title("Mean ReLU activity")
    axes[0].set_xlabel("Minibatch step")
    axes[0].set_ylabel(r"$m(t)=mean_b ReLU(w^T x_b)$")

    axes[1].set_title("Gate")
    axes[1].set_xlabel("Minibatch step")
    axes[1].set_ylabel(r"$g(t)$")

    axes[2].set_title("Raw update norm")
    axes[2].set_xlabel("Minibatch step")
    axes[2].set_ylabel(r"$||\Delta w||$")

    fig.suptitle(title, y=1.04)
    axes[0].legend()
    plt.tight_layout()
    plt.show()


def centered_gram(y):
    k = np.outer(y, y)
    return k - k.mean(axis=0, keepdims=True) - k.mean(axis=1, keepdims=True) + k.mean()


def upper_tri_corr(A, B):
    idx = np.triu_indices_from(A, k=1)
    a = A[idx] - A[idx].mean()
    b = B[idx] - B[idx].mean()
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    return float(a @ b / denom) if denom > 0 else np.nan


def relu_similarity_matching_score(X_eval, w, v1):
    """Compare learned ReLU output similarity to the ideal first-PC ReLU code.

    Because PCA direction is sign-invariant, compare against both +v1 and -v1.
    """
    h_learned = relu(X_eval @ w)
    score_pos = upper_tri_corr(centered_gram(h_learned), centered_gram(relu(X_eval @ v1)))
    score_neg = upper_tri_corr(centered_gram(h_learned), centered_gram(relu(X_eval @ (-v1))))
    return max(score_pos, score_neg)

# %% Experiment 1: IID Gaussian PCA
# Classic one-neuron Oja learns the first principal component. With our
# rule , E[ReLU(y)x] = 0.5 Cw for symmetric Gaussian data,
# so the expected direction is still the Oja/PCA direction.
d = 8
C, eigvecs, eigvals = make_covariance(d=d, seed=SEED)
v1 = eigvecs[:, 0]

n_train = 260_000
batch_size = 64
eta_hid = 0.08
alpha = 0.90
g_max = 2.0
lambda_oja = 1.0

X_iid = sample_gaussian(n_train, eigvecs, eigvals, rng)
w0 = 0.15 * unit_norm(rng.normal(size=d))

oja = run_single_relu_oja(
    X_iid,
    C,
    v1,
    w0,
    rule="oja",
    eta_hid=eta_hid,
    alpha=alpha,
    g_max=g_max,
    lambda_oja=lambda_oja,
    batch_size=batch_size,
    log_every=25,
)

accel = run_single_relu_oja(
    X_iid,
    C,
    v1,
    w0,
    rule="accel",
    eta_hid=eta_hid,
    alpha=alpha,
    g_max=g_max,
    lambda_oja=lambda_oja,
    batch_size=batch_size,
    log_every=25,
)

mag = run_single_relu_oja(
    X_iid,
    C,
    v1,
    w0,
    rule="magnitude",
    eta_hid=eta_hid,
    alpha=alpha,
    g_max=g_max,
    lambda_oja=lambda_oja,
    batch_size=batch_size,
    log_every=25,
)

results_iid = [oja, accel, mag]
plot_learning_curves(results_iid, "Single-neuron PCA, matched ReLU Hebbian-Oja rule", savepath="pca_dynamics.png")
plot_gate_and_updates(results_iid, "Gate and plasticity dynamics, matched ReLU rule", smooth=120)

X_eval = sample_gaussian(800, eigvecs, eigvals, rng)
for res in results_iid:
    score = relu_similarity_matching_score(X_eval, res.final_w, v1)
    print(
        f"{res.name:10s} | final alignment={res.align[-1]:.3f} "
        f"| variance={res.variance[-1]:.3f} | weight norm={res.weight_norm[-1]:.3f} "
        f"| ReLU similarity score={score:.3f}"
    )

#This matches Diego's intuition that in nondegenarate cases we get the same effect. Indeed, the our ReLU-Oja neuron still learns the
#first principal component.

# %% Experiment 2: Monte Carlo vector-field check for the matched rule
# This is the analytical intuition made numerical.
#
# For zero-mean Gaussian input and h = ReLU(w^T x),
#
#     E[h x]   = 0.5 Cw
#     E[h^2]   = 0.5 w^T C w
#
# so vanilla ReLU-Oja has the same expected vector-field direction as classic
# Oja, up to a factor of 0.5. With the accelerometer gate from the project, the
# expected update remains almost collinear with that Oja/PCA direction; the gate
# mainly changes the scalar speed of learning.
def relu_oja_expected_field(w, C, lambda_oja=1.0):
    s = float(w @ C @ w)
    return 0.5 * (C @ w - lambda_oja * s * w)


def monte_carlo_project_gated_field(
    w,
    eigvecs,
    eigvals,
    rng,
    n_mc_batches=8000,
    batch_size=64,
    alpha=0.90,
    g_max=2.0,
    lambda_oja=1.0,
):
    """Estimate E[g(t)(mean h x - lambda mean h^2 w)] for the project gate."""
    d = len(w)
    X_prev = sample_gaussian(n_mc_batches * batch_size, eigvecs, eigvals, rng)
    X = sample_gaussian(n_mc_batches * batch_size, eigvecs, eigvals, rng)
    X_prev = X_prev.reshape(n_mc_batches, batch_size, d)
    X = X.reshape(n_mc_batches, batch_size, d)

    h_prev = relu(X_prev @ w)
    h = relu(X @ w)
    m_prev = h_prev.mean(axis=1)
    m = h.mean(axis=1)

    # One-step gate with a(t-1)=0. This isolates whether the project gate
    # changes the direction of the expected local PCA update.
    r = np.maximum(0.0, m - m_prev)
    g = np.minimum(g_max, (1.0 - alpha) * r)

    hebb = (h[:, :, None] * X).mean(axis=1)
    post_second_moment = (h**2).mean(axis=1)
    updates = g[:, None] * (hebb - lambda_oja * post_second_moment[:, None] * w[None, :])
    return updates.mean(axis=0), float(g.mean())


def cosine(a, b, eps=1e-12):
    return float(a @ b / ((np.linalg.norm(a) + eps) * (np.linalg.norm(b) + eps)))


cosines, mean_gates = [], []
for _ in range(20):
    w = unit_norm(rng.normal(size=d))
    F_oja = relu_oja_expected_field(w, C, lambda_oja=lambda_oja)
    F_accel, mean_gate = monte_carlo_project_gated_field(
        w,
        eigvecs,
        eigvals,
        rng,
        n_mc_batches=8000,
        batch_size=batch_size,
        alpha=alpha,
        g_max=g_max,
        lambda_oja=lambda_oja,
    )
    cosines.append(cosine(F_oja, F_accel))
    mean_gates.append(mean_gate)

print(
    "Matched ReLU gate vector-field check: "
    f"mean cosine={np.mean(cosines):.4f}, "
    f"min cosine={np.min(cosines):.4f}, "
    f"mean one-step gate={np.mean(mean_gates):.5f}"
)

# %% Experiment 3: Fixed-input single-neuron dynamics
# If x_t = x* is fixed,
# then h(t) = ReLU(w_t^T x*) changes only because w_t changes during learning.
# Therefore r(t) = max(0, h(t)-h(t-1)) is literally a positive finite difference
# of the neuron's own activity over training time, matching the "activity
# derivative" intuition.
#
# ReLU caveat: if w_0^T x* <= 0, then h=0 and the local rule has a dead unit.
# We initialize with a small positive response so the single neuron can learn.
x_star = unit_norm(1.5 * eigvecs[:, 0] + 0.4 * eigvecs[:, 1])
orth_noise = rng.normal(size=d)
orth_noise = orth_noise - (orth_noise @ x_star) * x_star
w0_fixed = 0.20 * x_star + 0.50 * unit_norm(orth_noise)

X_fixed = np.repeat(x_star[None, :], 3500, axis=0)
C_fixed = np.outer(x_star, x_star)

oja_fixed = run_single_relu_oja(
    X_fixed,
    C_fixed,
    x_star,
    w0_fixed,
    rule="oja",
    eta_hid=0.20,
    alpha=0.92,
    g_max=1.0,
    lambda_oja=1.0,
    batch_size=1,
    log_every=10,
)

accel_fixed = run_single_relu_oja(
    X_fixed,
    C_fixed,
    x_star,
    w0_fixed,
    rule="accel",
    eta_hid=0.20,
    alpha=0.92,
    g_max=1.0,
    lambda_oja=1.0,
    batch_size=1,
    log_every=10,
)

plot_learning_curves(
    [oja_fixed, accel_fixed],
    "Fixed-input dynamics with the matched ReLU rule",
)
plot_gate_and_updates(
    [oja_fixed, accel_fixed],
    "For fixed input, the gate tracks positive activity change",
    smooth=50,
)

fig, ax = plt.subplots(figsize=(8, 4.2))
for res in [oja_fixed, accel_fixed]:
    ax.plot(moving_average(res.mean_activity, 50), label=res.name)
ax.set_title("Postsynaptic ReLU activity during fixed-input learning")
ax.set_xlabel("Training step")
ax.set_ylabel(r"$h(t)=ReLU(w_t^T x^*)$")
ax.legend()
plt.tight_layout()
plt.show()

# %% Experiment 4: Repeated/stationary episodes inside a PCA stream
# This mirrors the project story. We sample an input, repeat it several times,
# then move to a new input. Vanilla Oja keeps updating on repeated inputs.
# The accelerometer rule should allocate less raw plasticity to later repeats.
def make_repeated_stream(n_base, hold_len, eigvecs, eigvals, rng):
    base = sample_gaussian(n_base, eigvecs, eigvals, rng)
    X = np.repeat(base, hold_len, axis=0)
    repeat_position = np.tile(np.arange(hold_len), n_base)
    return X, repeat_position


hold_len = 12
X_rep, repeat_pos = make_repeated_stream(
    n_base=3500,
    hold_len=hold_len,
    eigvecs=eigvecs,
    eigvals=eigvals,
    rng=rng,
)
w0_rep = 0.20 * unit_norm(rng.normal(size=d))
eta_repeat = 0.003
oja_rep = run_single_relu_oja(
    X_rep,
    C,
    v1,
    w0_rep,
    rule="oja",
    eta_hid=eta_repeat,
    alpha=alpha,
    g_max=g_max,
    lambda_oja=lambda_oja,
    batch_size=1,
    log_every=100,
)

accel_rep = run_single_relu_oja(
    X_rep,
    C,
    v1,
    w0_rep,
    rule="accel",
    eta_hid=eta_repeat,
    alpha=alpha,
    g_max=g_max,
    lambda_oja=lambda_oja,
    batch_size=1,
    log_every=100,
)

plot_learning_curves(
    [oja_rep, accel_rep],
    "PCA stream with repeated stationary episodes",
)

mean_update_by_pos_oja = np.array(
    [oja_rep.update_norms[repeat_pos == k].mean() for k in range(hold_len)]
)
mean_update_by_pos_accel = np.array(
    [accel_rep.update_norms[repeat_pos == k].mean() for k in range(hold_len)]
)
mean_gate_by_pos_accel = np.array(
    [accel_rep.gates[repeat_pos == k].mean() for k in range(hold_len)]
)
relative_update_by_pos_oja = mean_update_by_pos_oja / mean_update_by_pos_oja[0]
relative_update_by_pos_accel = mean_update_by_pos_accel / mean_update_by_pos_accel[0]
accel_vs_oja_suppression = mean_update_by_pos_accel / mean_update_by_pos_oja

fig, axes = plt.subplots(1, 3, figsize=(16, 4.2))
axes[0].plot(np.arange(hold_len), mean_update_by_pos_oja, marker="o", label="oja")
axes[0].plot(np.arange(hold_len), mean_update_by_pos_accel, marker="o", label="accel")
axes[0].set_title("Absolute plasticity")
axes[0].set_xlabel("Position inside repeated-input episode")
axes[0].set_ylabel("Mean raw update norm")
axes[0].legend()

axes[1].plot(np.arange(hold_len), relative_update_by_pos_oja, marker="o", label="oja")
axes[1].plot(np.arange(hold_len), relative_update_by_pos_accel, marker="o", label="accel")
axes[1].axhline(1.0, color="0.5", linewidth=1, linestyle="--")
axes[1].set_title("Plasticity relative to onset")
axes[1].set_xlabel("Position inside repeated-input episode")
axes[1].set_ylabel("Mean update norm / onset update norm")
axes[1].legend()

axes[2].plot(np.arange(hold_len), mean_gate_by_pos_accel, marker="o", color="tab:orange")
axes[2].set_title("Accelerometer gate")
axes[2].set_xlabel("Position inside repeated-input episode")
axes[2].set_ylabel("Mean gate")

plt.tight_layout()
plt.savefig("pca_repeated_inputs.png", dpi=300, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(7, 4.2))
ax.plot(np.arange(hold_len), accel_vs_oja_suppression, marker="o", color="tab:green")
ax.axhline(1.0, color="0.5", linewidth=1, linestyle="--")
ax.set_title("Accelerometer update size relative to Oja")
ax.set_xlabel("Position inside repeated-input episode")
ax.set_ylabel("Mean accel update norm / mean Oja update norm")
plt.tight_layout()
plt.show()

tail_slice = repeat_pos > 0
onset_slice = repeat_pos == 0
for name, res in [("oja", oja_rep), ("accel", accel_rep)]:
    onset = res.update_norms[onset_slice].mean()
    tail = res.update_norms[tail_slice].mean()
    print(f"{name:6s} | tail/onset raw-update ratio = {tail / onset:.3f}")

# Interpretation of this last experiment:

#This supports our project's
#claim that the third factor regulates when Hebbian-Oja plasticity occurs, even
#when it does not change the basic PCA target learned by a single neuron.